version: '3.7'

services:
    app:
        build: ./app
        volumes:
            - ./app:/app
            - /app/node_modules
            - /app/public/app/dist
        ports:
            - 1234:1234
            - 44893:44893
        depends_on:
            - api

    api:
        build: ./api
        volumes:
            - ./api:/api
            - /api/node_modules
        ports:
            - 3000:3000
